[versions]
# Shadow plugin
shadow = "9.0.0-beta17"

# Core spigot
spigot_latest = "1.21.4-R0.1-SNAPSHOT"

# Protocol spigots
spigot_1_8_8 = "1.8.8-R0.1-SNAPSHOT"
spigot_1_9_0 = "1.9-R0.1-SNAPSHOT"
spigot_1_17_0 = "1.17-R0.1-SNAPSHOT"

# ProtocolLib
protocollib = "5.4.0"

# Guice
guice = "7.0.0"

# Annotation processors
jetbrains_annotations = "26.0.2"

# Testing
junit_jupiter = "5.9.2"
mockito = "5.17.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
# Core spigot
spigot_latest = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot_latest" }

# Protocol spigots
spigot_1_8_8 = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot_1_8_8" }
spigot_1_9_0 = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot_1_9_0" }
spigot_1_17_0 = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot_1_17_0" }

# ProtocolLib
protocollib = { group = "net.dmulloy2", name = "ProtocolLib", version.ref = "protocollib" }

# Guice
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }

# Annotation processors
jetbrains_annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains_annotations" }

# Testing
junit_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit_jupiter" }
junit_platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }